### ISSUE TITLE
recyclerView是不是有点问题的？

### ISSUE THREAD

**Issue by yubaokang** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#10]
只能显示一屏幕的数据？还是我使用有问题？

**Comment by captainbupt** [comment]
已有demo中能否复现？如不能，请给出一个简单demo

**Comment by yubaokang** [comment]
解决了，加了这两个就OK了
@Override
            public boolean checkCanDoLoadMore(PtrFrameLayout frame, View content, View footer) {
                return super.checkCanDoLoadMore(frame, recyclerView, footer);
            }

```
        @Override
        public boolean checkCanDoRefresh(PtrFrameLayout frame, View content, View header) {
            return super.checkCanDoRefresh(frame, recyclerView, header);
        }
```

多谢了。
