### ISSUE TITLE
上拉刷新和下拉刷新是共用最后刷新时间的？

### ISSUE THREAD

**Issue by hegelsu** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#11]
两个问题：
1. 有无办法解决分开统计上拉时间和下拉时间
2. 由于head和footer共用的一个xml,导致想修改下面的文字时发现修改到上面去了，或者说下方的加载更多一般不需要时间，这个如何修改？

**Comment by captainbupt** [comment]
请自定义满足需求的上拉和下拉效果
