### ISSUE TITLE
scrollView 顶部viewpager 滑动和下拉有点冲突

### ISSUE THREAD

**Issue by yubaokang** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#14]
嵌套scrollView 顶部如果是viewpager的话，滑动viewpager会跟下拉刷新冲突；
只有当水平滑动或者水平偏上滑动viewpager才能滑动viewpager，只要有一点点水平偏下滑动viewpager的话，就会触发下拉。

**Comment by captainbupt** [comment]
请使用disableWhenHorizontalMove方法
