### ISSUE TITLE
下拉刷新+头部是ViewPager,冲突如何处理？

### ISSUE THREAD

**Issue by yubaokang** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#15]
下拉刷新+头部是ViewPager,冲突如何处理？

**Comment by captainbupt** [comment]
没懂。给个小demo？

**Comment by zt80hou** [comment]
case MotionEvent.ACTION_MOVE:
                mLastMoveEvent = e;
                mPtrIndicator.onMove(e.getX(), e.getY());
                float offsetX = mPtrIndicator.getOffsetX();
                float offsetY = mPtrIndicator.getOffsetY();

                // 修复Banner左右滑动和下拉刷新 事件冲突
                if (Math.abs(offsetX) > Math.abs(offsetY)) {
                    return dispatchTouchEventSupper(e);
                }

//                if (mDisableWhenHorizontalMove && !mPreventForHorizontal && (Math.abs(offsetX) > mPagingTouchSlop && Math.abs(offsetX) > Math.abs(offsetY))) {
//                    if (mPtrIndicator.isInStartPosition()) {
//                        mPreventForHorizontal = true;
//                    }
//                }
//                if (mPreventForHorizontal) {
//                    return dispatchTouchEventSupper(e);
//                }

                boolean moveDown = offsetY > 0;
                boolean moveUp = !moveDown;
