### ISSUE TITLE
使用Scrollview上拉加载问题

### ISSUE THREAD

**Issue by wudouxingjun** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#16]
使用in.srain.cube.views.ptr.PtrClassicFrameLayout包含ScrollView，当内容不足一屏时，设置Mode为Refresh时，刷新时，尾部布局自动出现，并出现而且布局没有移动，刷新完后显示更新完成，不能消失

**Comment by huangpy** [comment]
遇到同样的问题，这是个蛮严重的bug，我的处理办法是在PtrClassicFrameLayout增加设置能否上拉加载的方法（本质是设置Mode和隐藏footer）

```
 public void hideFooter() {
        mPtrClassicFooter.setVisibility(INVISIBLE);
    }

    public void showFooter() {
        mPtrClassicFooter.setVisibility(VISIBLE);
    }

    //设置是否能上拉加载
    public void enablePullLoad(boolean enabled) {
        if (enabled) {
            showFooter();
            setMode(Mode.BOTH);
        } else {
            hideFooter();
            setMode(Mode.REFRESH);
        }
    }
```

然后在回调里检查服务器返回的数据是否有小于请求的数目，if true，则设置不能加载更多

**Comment by captainbupt** [comment]
这个问题确实没有考虑到。因为我一般滑动布局都会设置到满屏，或者上下都有内容物进行填充。目前可以暂时按上面说的做一下。

**Comment by captainbupt** [comment]
Please check the demo for TextView in 1.0.5 and tell me if you have more problem.
