### ISSUE TITLE
if a view height is wrap_content

### ISSUE THREAD

**Issue by lodaDuan** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#17]
if a view height is wrap_content, then it will display loadmore view.
such as EvenOnlyATextView Fragment, set TextView height wrap_content.

**Comment by captainbupt** [comment]
Please check the demo for `TextView` in 1.0.5 and tell me if you have more problem.

**Comment by lodaDuan** [comment]
Only set TextView's height wrap_content,PtrClassicFrameLayout's height is match_parent
It still has the same problem. I means loadmore view can hide when refreshing

**Comment by captainbupt** [comment]
Could you give me a example case when the content's height is wrap_content and PtrClassicFrameLayout's height is match_parent? 
Anyway, I think I got your point. So, you need the loadmore view be invisible before and after refreshing, is that right?

**Comment by lodaDuan** [comment]
Such as EvenOnlyATextView Fragment, set TextView height wrap_content, and PtrClassicFrameLayout's height is match_parent.

**Comment by lodaDuan** [comment]
It seems loadmore view still visible

**Comment by captainbupt** [comment]
I mean "why not set PtrClassicFrameLayout's height as wrap_content"?
