### ISSUE TITLE
请问可以设置左拉刷新，右拉加载更多吗

### ISSUE THREAD

**Issue by tommyfeng** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#19]
要如何能够设置成左拉和右拉呢？

**Comment by captainbupt** [comment]
这个暂时没考虑。改起来成本比较高，考虑其他的库吧。

**Comment by tommyfeng** [comment]
@captainbupt 嗯，谢谢你的回复。项目中已经使用到了这个库，觉得挺不错的。就想尝试看看能不能左拉和右拉。嘿嘿！

**Comment by zhouzl18** [comment]
我的项目中也使用了这个库，很好用

2016-10-14 16:02 GMT+08:00 Weizhou He notifications@github.com:
