### ISSUE TITLE
设置自定义底部时的一个Bug

### ISSUE THREAD

**Issue by ITshihao** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#20]
PtrFrameLayout类中的setFooterView（）方法有问题   会导致我一旦重新自定义一个底部view的话就会removeView（mHeaderView）把header给去掉了  实际上应该去掉的是默认的footer

应该改为 public void setFooterView(View footer) {
        if (mFooterView != null && footer != null && mFooterView != footer) {
            removeView(mFooterView);
        }
        ViewGroup.LayoutParams lp = footer.getLayoutParams();
        if (lp == null) {
            lp = new LayoutParams(-1, -2);
            footer.setLayoutParams(lp);
        }
        mFooterView = footer;
        addView(footer);
    }

源代码  是这样的  你看看
    public void setFooterView(View footer) {
        if (mFooterView != null && footer != null && mHeaderView != footer) {
            removeView(mHeaderView);
        }
        ViewGroup.LayoutParams lp = footer.getLayoutParams();
        if (lp == null) {
            lp = new LayoutParams(-1, -2);
            footer.setLayoutParams(lp);
        }
        mFooterView = footer;
        addView(footer);
    }g

**Comment by captainbupt** [comment]
已修复，非常感谢！
