### ISSUE TITLE
项目跑不起来~

### ISSUE THREAD

**Issue by lijie815917** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#21]

**Comment by zhouzl18** [comment]
我这边可以，你看下是报的什么问题

2016-11-03 16:43 GMT+08:00 lijie815917 notifications@github.com:

**Comment by lijie815917** [comment]
我直接用lib库是可以，但是项目clone后不直接跑，gradle失败，是不是过滤掉了一些配置文件导致没上传

**Comment by captainbupt** [comment]
你是想直接运行demo嘛？在setting.gradle里面，应该是`include 'ptr-demo',':ptr-lib'`，上传的时候忘了改回来了。

**Comment by lijie815917** [comment]
恩恩，谢谢哈
