### ISSUE TITLE
上拉加载更多体验不好

### ISSUE THREAD

**Issue by yb755** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#22]
当上拉加载显示加载完成后，想马上看加载出来的更多的内容，显示不了，需要等大约半秒后才可以。

见意，加载更多显示加载完后成。主页面不要下移，直接隐掉footer，然后新内容直接显示填充到footer的位置。

**Comment by captainbupt** [comment]
原理并不是这样的。而且还有比较复杂的情况，比如加载完成后并没有新增数据。
你可以把duration_to_close_footer设置为0，加载完成后，自行根据不同的view进行相应的位移即可。

**Comment by hugoFather** [comment]
这个上拉加载的效果真心不咋好= = 我将duration_to_close_footer设置为0后 使用recylcerview的srollBy方
法，还是好像这个上拉完成后还固定了一个延迟时间，导致上拉完成

**Comment by hugoFather** [comment]
这个上拉加载的效果真心不咋好= = 我将duration_to_close_footer设置为0后 使用recylcerview的srollBy方
法，还是好像这个上拉完成后还固定了一个延迟时间，导致上拉完成后 我的view进行相关位移 但是上拉的动画还在执行，博主有没什么好的办法起码让这个动画正常点。。。
