### ISSUE TITLE
能否在上拉加载更多的时候，底部加载动画结束后，不回弹，数据直接填充到底部的刷新动画那个位置？

### ISSUE THREAD

**Issue by neo1201** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#25]
![image](https://cloud.githubusercontent.com/assets/5358278/20291245/d80a6dd4-ab1f-11e6-9e2a-aafd79fbce1e.png)

**Comment by captainbupt** [comment]
不能。参考 #22
