### ISSUE TITLE
加载更多

### ISSUE THREAD

**Issue by forestAndroid** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#26]
加载更多.在加载完成后，“加载完成.”四个字没有消失。出现的几率不大，偶尔会出现这种情况
![image](https://cloud.githubusercontent.com/assets/10668022/20553863/b3cb794e-b192-11e6-9eca-f824be35ba1f.png)；正常加载完是：
![image](https://cloud.githubusercontent.com/assets/10668022/20553872/d1b2572a-b192-11e6-9641-b6aba11393c9.png)

**Comment by captainbupt** [comment]
demo中能否复现？如果不能，麻烦给出一个使用demo

**Comment by forestAndroid** [comment]
异常情况：






正常情况：









操作：请上拉的距离大点，手指拉到状态栏那里，出现这种异常情况的几率大。


CusPtrClassicFrameLayout继承了PtrClassicFrameLayout

解决嵌套banner时滑动冲突

**Comment by xj189** [comment]
为什么会出现两个动画

**Comment by captainbupt** [comment]
@xj913492952  demo中能否复现？如果不能，麻烦给出一个使用demo

**Comment by xj189** [comment]
有时候高度不用matchparent就会那样

**Comment by captainbupt** [comment]
move to #30
