### ISSUE TITLE
loadmore时的bug

### ISSUE THREAD

**Issue by luvictor** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#28]
1、连续loadmore的时候，会一直显示加载完成。
2、loadmore之后，必须再向上滑动一下才能看到新的内容。

**Comment by Liloupar** [comment]
我也碰到了这个问题
求问解决方式

**Comment by chemin233** [comment]
我也遇到了这个问题,解决了吗?

**Comment by autoool** [comment]
这个库遇到问题，没有人回答解决？

**Comment by captainbupt** [comment]
1、请问demo中是否存在这个问题？
2、该效果基于目前的实现方式是无法实现的。

**Comment by autoool** [comment]
我没有测试，只是看了一下，这里的问题都没有人回复。

**Comment by Liloupar** [comment]
@captainbupt 
1 存在
2 这个描述的是bug的现象而不是说需求

**Comment by chemin233** [comment]
@captainbupt demo中也有这个问题,有好的解决方案吗?

**Comment by captainbupt** [comment]
我理解还是没回弹完成，然后连续上拉导致的问题。setForceBackWhenComplete(true) 应该能解决问题。参照 #4
