### ISSUE TITLE
是否在Release 1.0.1时没有执行Clean操作?

### ISSUE THREAD

**Issue by Muyangmin** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#3]
我的gradle依赖是这样写的：

``` Groovy
compile 'in.srain.cube:ptr-load-more:1.0.1'
```

但是仍然存在Issue #2 的问题。起初以为是我的工程没有刷新，多次执行`gradle clean`后问题仍然存在，所以我在项目中使用Cmd+Shift+O，分别打开下面两个PtrFrameLayout文件:
-  {project}/build/intermediates/exploded-aar/in.srain.cube/ptr-load-more/1.0.1/jars/classes.jar!/in/srain/cube/views/ptr/PtrFrameLayout.class 
-  {user}/.gradle/caches/modules-2/files-2.1/in.srain.cube/ptr-load-more/1.0.1/190d22489ebf866d83da715fe5a094648c3cf9ab/ptr-load-more-1.0.1-sources.jar!/in/srain/cube/views/ptr/PtrFrameLayout.java  

在AS的提示里，第一个是ptr-load-more-1.0.1.jar, 另一个是ptr-load-more-1.0.1-sources.jar。问题出现了！
在第一个里，看到的是这样：

``` Java
    private static final boolean DEBUG_LAYOUT = true;
    public static boolean DEBUG = true;
```

而另一个长这样：

``` Java
    private static final boolean DEBUG_LAYOUT = false;
    public static final boolean DEBUG = false;
```

我将jcenter的[aar文件](http://jcenter.bintray.com/in/srain/cube/ptr-load-more/1.0.1/:ptr-load-more-1.0.1.aar)单独下载解压，使用jd-gui**反编译，看到的变量值也为true**。

所以，请允许我冒昧揣测一下，是不是在release的时候并没有clean操作？能否重新上传一个版本到jcenter，Thanks。

**Comment by captainbupt** [comment]
Thank you for your advice. It should be fixed know in version 1.0.2

BTW, you could still turn on the debug option by using `PtrFrameLayout.DEBUG = true` in your code.
