### ISSUE TITLE
下拉刷新出现footer的信息(上拉加载)

### ISSUE THREAD

**Issue by zhouzl18** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#30]
我的根视图是<com.yyydjk.library.DropDownMenu/>;
在代码中动态的将PtrClassicFrameLayout 添加进DropDownMenu(条件筛选控件)，设置ptrCFL.setPtrHandler(new PtrDefaultHandler2(){...}); 下拉刷新的时候就会出现footer.
请问这个该如何解决？

**Comment by captainbupt** [comment]
下拉刷新出现footer是通常是因为父布局和子布局底边不对齐导致的。因为header和footer都是贴着子布局上部和下部添加进去的，通常情况下，父布局和子布局的上边是对齐的，但是下边却不一定（比如，父布局是match_parent，而子布局是wrap_content）。
