### ISSUE TITLE
作者您好，您的这个封装十分好，但是感觉就是少了一种模式

### ISSUE THREAD

**Issue by liyuhaolol** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#35]
现在你只有2个模式，单独下拉刷新模式PtrDefaultHandler，下拉，上拉模式PtrDefaultHandler2，但是仔细想想，诸如搜索记录这种使用场景，是个单独上拉刷新模式，所以，现在差一种使用场景，希望作者可以加上这最后一种使用场景，我是使用您的源码自己封装了下，但是我感觉您封装出来一个额外的接口，供给大家使用更好，麻烦您阅读了！

**Comment by captainbupt** [comment]
没懂你意思，搜索记录？。。。你可以直接提交一个pull request

**Comment by liyuhaolol** [comment]
我只是说了一个使用场景而已，现在handler确实你只有2个，1个同时存在的，1个只有下拉的，是不是缺少一个只有上拉的handler呢？我只是推荐您可以加上，完善一下

**Comment by captainbupt** [comment]
可以通过setMode(Mode. LOAD_MORE)来实现，使用handler2，忽略下拉方法即可。

**Comment by liyuhaolol** [comment]
我知道的，这么做，反正还是会有无关代码的干扰，看起来不清净，所以才推荐您，能更新多一个api而已

**Comment by 1024042400** [comment]
哈哈, 我是不知道有setMode(Mode. LOAD_MORE)这个方法, 找了半天.
不过handler如果有3种模式会更清晰. 1:同时存在. 2:只有下拉. 3:只有上拉.
