### ISSUE TITLE
下拉刷新和Viewpager的左右滑动问题

### ISSUE THREAD

**Issue by zhouzl18** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#38]
在我布局中有viewpager,当我左右滑动的时候（向斜下方滑动），就会触发下拉刷新，这里能不能判断一下，如果是左右滑动，就不触发下拉刷新？

**Comment by captainbupt** [comment]
请调用disableWhenHorizontalMove，设置为true

**Comment by zhouzl18** [comment]
我掉用了，但依然会存在体验不好的情况，稍微往下滑，就会带动刷新
