### ISSUE TITLE
作者你好,今天遇到一个问题

### ISSUE THREAD

**Issue by weimingjue** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#39]
用这个控件里面是recyclerview,recyclerview的第一个条目是viewpager,当我滑动viewpager的时候会很容易触发下拉效果,这样会导致viewpager很难翻页,应该是廖虎秋的下拉在顶部的时候太灵敏了,能有解决方案吗

**Comment by captainbupt** [comment]
请调用disableWhenHorizontalMove，设置为true
