### ISSUE TITLE
连续向上滑动受阻

### ISSUE THREAD

**Issue by Freshman111** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#4]
谢谢你加入了加载更多的功能，但是连续向上滑动的时候，好像有时不能滑动，或者有助力

**Comment by captainbupt** [comment]
添加了方法`mPtrFrame.setForceBackWhenComplete(true);`，默认为false。
还没有发版，你可以下载下来，用demo测试一下，看能否满足需求

**Comment by Freshman111** [comment]
谢谢，已经满足了，（不过相比起来连续滑动还是没有下拉顺滑）

**Comment by yangghost** [comment]
什么时候发新版本.我的也是上拉加载更多的时候感觉不是很顺畅.
