### ISSUE TITLE
能否实现上拉到一半就开始加载数据

### ISSUE THREAD

**Issue by yangghost** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#5]
能否实现上拉到一半或者三分之二就开始自动加载下一页数据.不用非要到拉到底部还要再下拉才能加载数据.

**Comment by xj189** [comment]
这个也是我fork别人的，这个上啦还不完善，我也在研究，有点麻烦

**Comment by captainbupt** [comment]
没太懂你的需求。
你可以继承PtrFrameLayout，然后重写onUIPositionChange方法，里面的PtrIndicator可以随时获取当前位置。

**Comment by yangghost** [comment]
自己在recycleview写一个addOnScrollListener方法就可以了
