### ISSUE TITLE
自动显示“正在加载”可以实现吗？

### ISSUE THREAD

**Issue by ligangcc** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#6]
现在好多App，都是滚动到底部以后，就自动显示一条“正在加载”的内容，请问现有的代码通过设置属性可以实现吗？ 我看现在是到底以后，再要pull一下才能显示。

**Comment by captainbupt** [comment]
大部分app都是在footer里面显示加载状态，所以滑动起来会比较顺畅。可以监听listview或者其它view滚动到底的事件，然后调用autoRefresh，应该可以实现类似效果。还在尝试更好的解决方案。

**Comment by ligangcc** [comment]
谢谢，我现在是在Listview里面加了footer来实现，如果后面你们能搞成通用的就好了。

我的建议是：再增加一种模式，显示的话现有的footer已经可以实现了，只是在拖动上要处理一下，拖到底部的时候，
自动把footer显示出来，而且只能拖动footer那么高，然后通知app去刷新。

在 2016-05-03 13:18:52，"Weizhou He" notifications@github.com 写道：

大部分app都是在footer里面显示加载状态，所以滑动起来会比较顺畅。可以监听listview或者其它view滚动到底的事件，然后调用autoRefresh，应该可以实现类似效果。还在尝试更好的解决方案。

**Comment by eicky** [comment]
我觉得可以把自动加载加上去，加一个设置的方法

**Comment by eicky** [comment]
就是在加载更多的时候

**Comment by captainbupt** [comment]
自动加载的话，在本身的父控件应该是无法捕捉到的。基本的思路就是给子控件设置监听，诸如监听scrollview或者listview滑动到底部，这个是没问题的。但是如何方便的去集成这个东西，同时考虑兼容性方面的问题，欢迎去做一下尝试。

**Comment by huangpy** [comment]
恩，最好放在可滑动控件里区检查。
如果是recyclerview，我用的[EndlessRecyclerOnScrollListener.java](https://gist.github.com/ssinss/e06f12ef66c51252563e)，然后在给recyclerview添加此监听：

```
 mRecycler.addOnScrollListener(new EndlessRecyclerOnScrollListener(mLinearLayoutManager) {
            @Override
            public void onLoadMore(int current_page) {
                //自动加载的事情
            }
        });
```

**Comment by huangpy** [comment]
但是我上面那种自动更新并没有后progressbar，如果集成一个进去以后再看
