### ISSUE TITLE
当 PtrClassicFrameLayout 内部嵌套Layout ->List 

### ISSUE THREAD

**Issue by llkkzz111** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#8]
当 PtrClassicFrameLayout 内部嵌套Layout ->List 的时候上拉高度计算错误，导致内容显示不全

**Comment by captainbupt** [comment]
你好，没有太明白你的意思。你是PtrClassicFrameLayout-> Layout->List？如果是这样的话，你需要自己实现PtrHandler2类，并通过set方法设置。你可以利用PtrDefaultHandler2中的静态方法，不过要传递正确的view，比如在这里就应该传递List。

**Comment by llkkzz111** [comment]
<in.srain.cube.views.ptr.PtrClassicFrameLayout xmlns:cube_ptr="http://schemas.android.com/apk/res-auto"
        android:id="@+id/rotate_header_grid_view_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/cube_mints_f1f1f1"
        cube_ptr:ptr_duration_to_close_either="1000"
        cube_ptr:ptr_keep_header_when_refresh="true"
        cube_ptr:ptr_pull_to_fresh="false"
        cube_ptr:ptr_ratio_of_header_height_to_refresh="1.2"
        cube_ptr:ptr_resistance="1.7">

```
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <GridView
            android:id="@+id/rotate_header_grid_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/cube_mints_white"
            android:fadingEdge="none"
            android:focusable="false"
            android:horizontalSpacing="10dp"
            android:listSelector="@android:color/transparent"
            android:numColumns="2"
            android:paddingBottom="12dp"
            android:paddingLeft="12dp"
            android:paddingRight="12dp"
            android:scrollbars="none"
            android:stretchMode="columnWidth" />
    </LinearLayout>
</in.srain.cube.views.ptr.PtrClassicFrameLayout>
```

类似这种情况

**Comment by captainbupt** [comment]
那可以按我说的试试，应该没问题。调用`setPtrHandler`方法

**Comment by llkkzz111** [comment]
我是通过修改 源码 验证过
存在这个问题
包括 android-Ultra-Pull-To-Refresh  也有类似的情况

**Comment by captainbupt** [comment]
能否给个demo看一下？

**Comment by llkkzz111** [comment]
直接在ListView或者GridView外面嵌套一个linear layout就可以了

**Comment by captainbupt** [comment]
嗯。但是我测试是没有问题的。

**Comment by llkkzz111** [comment]
已经将编译好的apk发送到  weizhou.captain.he@gmail.com

**Comment by captainbupt** [comment]
一看就没理解我在说什么。。。自己看新commit的demo吧。
