### ISSUE TITLE
快速上拉加载更多有时候会列表全消失

### ISSUE THREAD

**Issue by LongAgoLong** [captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More#9]
快速上拉加载更多有时候会列表全消失了，求解决……

**Comment by captainbupt** [comment]
已有demo中能否复现？如不能，请给出一个简单demo

**Comment by LongAgoLong** [comment]
监听listview滑动到底部调用autolodemore方法的时候偶尔会出现，感觉就像卡了一下，listview部分就全变空白了，再点击一下屏幕就正常了 发自网易邮箱大师 在2016年06月14日 12:36 ，Weizhou He写道： 已有demo中能否复现？如不能，请给出一个简单demo — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wudouxingjun** [comment]
Scrollview嵌套listview会出现问题

**Comment by wudouxingjun** [comment]
Scrollview里面的内容会显示不全，就只显示一屏的数据，在底部会有上拉加载，这个项目还是有很大的问题啊

**Comment by LongAgoLong** [comment]
用NestScrollViewba
